### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by vilinski** [Hopac/Hopac#212]
Sadly I have no Idea how to reproduce it

comes periodically after significant error free execution time like a couple of minutes

```
System.Exception: Exception raised by job
 ---> System.BadImageFormatException: Bad IL range.
   at Hopac.Core.ContMap`2.DoWork(Worker& wr)
   at Hopac.Ch`1.TryAlt(Worker& wr, Int32 i, Cont`1 xK, Else xE)
   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
   --- End of inner exception stack trace ---
   at Hopac.Scheduler.run[x](Scheduler sr, Job`1 xJ) in C:\projects\hopac\Libs\Hopac\Hopac.fs:line 489
   at Hopac.Job.Global.run[x](Job`1 xJ) in C:\projects\hopac\Libs\Hopac\Hopac.fs:line 865
   at Hopac.Hopac.run[x](Job`1 x) in C:\projects\hopac\Libs\Hopac\TopLevel.fs:line 14
   at <StartupCode$FSI_0015>.$FSI_0015.main@()
Stopped due to error
> 
```

Hopac: 0.5.0
OS: MacOS Big Sur 11.2.3
executed a script using `dotnet fsi script.fsx`
Output of `dotnet --info`:

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.404 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by haf** [comment]
Tried compiling this project yourself on .Net 5?

**Comment by RahimovIR** [comment]
I get an error on linux
```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
   at Hopac.Stream.wrapMain@725.Invoke(Promise`1 xs)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
Остановлено из-за ошибки
```
fsx script:
```fsharp
#r "nuget: Hopac, 0.5.1"

open Hopac

let tmp = [ 0; 0; 0; 1; 1; 1; 2; 2; 2; 3; 3; 3 ]

tmp
|> Stream.ofSeq
|> Stream.groupByFun (fun k _ s -> k) id
|> Stream.toSeq
|> run
```
ran in vscode, process list:
/usr/bin/dotnet fsi
dotnet exec /usr/share/dotnet/sdk/5.0.400/FSharp/fsi.dll

```
dotnet --info
Пакет SDK для .NET (отражающий любой global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Среда выполнения:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.412 [/usr/share/dotnet/sdk]
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by RahimovIR** [comment]
This error occurs if the Hopac library is compiled with dotnnet 5, if compiled with version 2 or 3 everything works.

**Comment by RahimovIR** [comment]
This test also fails
https://github.com/Hopac/Hopac/blob/e66c88ef11ba1bb00698c6eba46dcb851c2929df/Tests/AdHocTests/StreamTests.fs#L129

**Comment by haf** [comment]
I'm not writing F# during my day work any longer, but I could look into merging PR:s if I receive them. Thanks for debugging @RahimovIR

**Comment by RahimovIR** [comment]
@haf created #213 but I want to note that changing the dotnet version does not solve the @vilinski problem, since it has an error on version 5.0

**Comment by raycheung** [comment]
This issue also happens when using .net8, hope it could be fixed.
